version: '2.1'


services: 
    zen_money_users:
        image: zen_money_users 
        container_name: zen_money_users
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - DB_CONNECTION_STRING=mongodb://zen_mongo:27017/zen-db
        depends_on:
            - zen_mongo
        ports: 
            - "4000:3000"

    zen_mongo:
        image: mongo
        container_name: zen_mongo
        ports: 
            - "27017:27017"
        
